export const PRODUCTS = [
    {
        id:1,
        productName:"Shalimar",
        productBrand:"Guerlain",
        productType:"Eau de Parfum",
        price:150,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id: 2,
        productName:"La Vie est Belle",
        productBrand:"Lancome",
        productType:"Eau de Parfum",
        price: 80,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id: 3,
        productName:"Portrait of a Lady",
        productBrand:"Frederic Malle",
        productType:"Eau de Parfum",
        price: 400,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id:4,
        productName:"Baccarat Rouge 540",
        productBrand:"Maison Francis Kurkdjian",
        productType:"Extrait de Parfum",
        price:400,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id:5,
        productName:"La Rhapsodie Noir",
        productBrand:"Dusita Parfums",
        productType:"Eau de Parfum",
        price:225,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id:6,
        productName:"Hummingbird",
        productBrand:"Zoologist",
        productType:"Extrait de Parfum",
        price:225,
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
    {
        id:7,
        productName:"",
        productBrand:"",
        price:"",
        productImage:"",
        productCopy:"",
        topNotes:"",
        heartNotes:"",
        baseNotes:"",
    },
]